wip

diff --git a/.github/workflows/Lib edFi.ods.common manual.yml b/.github/workflows/Lib edFi.ods.common manual.yml
--- a/.github/workflows/Lib edFi.ods.common manual.yml
+++ b/.github/workflows/Lib edFi.ods.common manual.yml
@@ -23,6 +23,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'simpat-adam' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "Missing Azure Access Token" 
+        exit 1 
     - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # 2.1.0
@@ -61,6 +66,7 @@ jobs:
         .\build.githubactions.ps1 InstallCredentialHandler
       shell: pwsh
     - name: publish
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -Solution "Application/EdFi.Ods.Common/EdFi.Ods.Common.sln" -ProjectFile "Application/EdFi.Ods.Common/EdFi.Ods.Common.csproj"  -PackageName "EdFi.Suite3.Ods.Common"
       shell: pwsh
diff --git a/.github/workflows/Pkg EdFi.Ods.Populated.Template.yml b/.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
--- a/.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
+++ b/.github/workflows/Pkg EdFi.Ods.Populated.Template.yml
@@ -30,7 +30,7 @@ env:
   HEAD_REF:  ${{ GITHUB.HEAD_REF }}
   REF_NAME:  ${{ GITHUB.REF_NAME }}
   REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
-  
+
 jobs:
   build:
 
@@ -39,6 +39,11 @@ jobs:
     steps:
     - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
       run:  echo "${{ github.event.inputs.distinct_id }}"
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'simpat-adam' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "Missing Azure Access Token" 
+        exit 1 
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # 2.1.0
       with:
@@ -151,6 +156,7 @@ jobs:
           }
       shell: pwsh
     - name: publish 
+      if: ${{ env.AZURE_ARTIFACT_NUGET_KEY != '' }}
       working-directory: ./Ed-Fi-ODS/
       run: |
         .\build.githubactions.ps1 publish -InformationalVersion ${{ env.INFORMATIONAL_VERSION }} -BuildCounter ${{ github.run_number }} -BuildIncrementer ${{env.BUILD_INCREMENTER}} -NuGetApiKey ${{ env.AZURE_ARTIFACT_NUGET_KEY }} -EdFiNuGetFeed ${{env.AZURE_ARTIFACT_URL}} -PackageName  "EdFi.Suite3.Ods.Populated.Template"
