wip

diff --git a/.github/workflows/Pkg EdFi.Ods.CodeGen.yml b/.github/workflows/Pkg EdFi.Ods.CodeGen.yml
--- a/.github/workflows/Pkg EdFi.Ods.CodeGen.yml
+++ b/.github/workflows/Pkg EdFi.Ods.CodeGen.yml
@@ -23,7 +23,7 @@ env:
   REPOSITORY_DISPATCH_BRANCH: ${{ github.event.client_payload.branch }}
   HEAD_REF:  ${{ GITHUB.HEAD_REF }}
   REF_NAME:  ${{ GITHUB.REF_NAME }}
-  REPO_NAME: ${{ GITHUB.REPOSITORY_OWNER }}
+  REPOSITORY_OWNER: ${{ GITHUB.REPOSITORY_OWNER }}
 
 jobs:
   build:
@@ -31,11 +31,13 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check for secret
-      if: ${{ env.REPO_NAME == 'simpat-adam' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
-      run: exit 1 
     - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
       run:  echo "${{ github.event.inputs.distinct_id }}"
+    - name: Check for Azure token
+      if: ${{ env.REPOSITORY_OWNER == 'simpat-adam' && env.AZURE_ARTIFACT_NUGET_KEY == '' }}
+      run: | 
+        echo "Missing Azure Access Token" 
+        exit 1 
     - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
     - name: Setup .NET
       uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # 2.1.0
